## These two functions are used to create, what I will call, matrix-list 
## objects and to eliminate redundant inverse calculations. 
## The matrix-list objects are created by the makeCacheMatrix function
## and store the value of a matrix and its inverse. A matrix's inverse 
## can then be checked and updated by the cacheSolve function.


## The makeCacheMatrix function creates a matrix-list object 
## that stores both the matrix and its inverse. It returns 
## a list of four conveniently callable methods used to 
## set or retrieve the matrix and inverse.
## Note: The function's argument must be a square, invertible matrix.

makeCacheMatrix <- function(x = matrix()) {
    
    inv.matrix<-NULL ## Deletes the inverse if one is already stored.
    
    ## Method that sets the new matrix and then deletes the cached inverse.    
    ##Note: "<<-" is used to scope to the parent environment, so that 
    ##these variables are retrievable by the get methods within the function.
    set.matrix<-function(new.matrix){ 
    
        x<<-new.matrix 
        inv.matrix<<-NULL    
    }
    
    ## Method to retrieve the stored matrix.
    get.matrix <- function() x 
    
    ## Method takes a user defined inverse and 
    ##replaces the internally stored inverse.
    set.inv <- function(user.inv) inv.matrix <<- user.inv 
    
    ## Method to retrieve the stored matrix.
    get.inv <- function() inv.matrix 
    
    
    ## Create a list that is callable by the user or other functions.
    list(set.matrix = set.matrix, get.matrix = get.matrix, 
         set.inv = set.inv, get.inv = get.inv)

} ## End makeCacheMatrix




## The cacheSolve function works in conjunction with matrix-list objects 
## created by the makeChaceMatrix function. The cacheSolve function takes 
## a matrix-list object generated by makeCacheMatrix as its input, checks
## if the inverse has already been calculated, and finds the inverse and
## updates the matrix-list object if needed.

cacheSolve <- function(x, ...) {
    
    ## Gets the inverse matrix (or NULL value) stored by the makeCacheMatrix function.
    i.matrix <- x$get.inv() 
    
    ## Checks if the inverse already exists in the makeCacheMatrix object.
    if(!is.null(i.matrix)) { 
        ## If an inverse is already stored, alerts the user,  
        ## and returns the stored value.
        message("getting cached data") 
        return(i.matrix) 
    }

    ## If no inverse is stored, this: 
    ## gets the stored, original matrix and finds its inverse.
    i.matrix <- solve(x$get.matrix()) 
    ## sets the inverse matrix in the makeCacheMatrix object,
    x$set.inv(i.matrix) 
    ## and returns the value to the user.
    i.matrix 
} ## End chacheSolve
 

# Example of Use:
# 
# > source("cachematrix.R")
# > testMatrix<-matrix(c(12,6,9,1), nrow=2, ncol=2)
# > testMatrix
#       [,1] [,2]
# [1,]   12    9
# [2,]    6    1
# > testMatrixList<-makeCacheMatrix(testMatrix)
# > cacheSolve(testMatrixList)
#              [,1]       [,2]
# [1,] -0.02380952  0.2142857
# [2,]  0.14285714 -0.2857143
# > cacheSolve(testMatrixList)
# getting cached data
# [,1]       [,2]
# [1,] -0.02380952  0.2142857
# [2,]  0.14285714 -0.2857143
